shared:
    image: node:6
    annotations:
         screwdriver.cd/cpu: MICRO
         screwdriver.cd/disk: LOW
jobs:
    job1:
        requires: [~commit, ~pr]
        steps:
            - echo: echo hello
    job2:
        requires: [~job1]
        steps:
            - echo: echo bye
